language: node_js
node_js:
  - "8"
  - "7"
install:
  - npm install
env:
  -MONGODB_URI=mongodb://localhost/chat
  -MONGODB_TEST=mongodb://localhost/chat_test
services:
- mongodb
script:
  - npm run test
